"""empty message

Revision ID: bace61fe2b79
Revises: 055c6a993116
Create Date: 2018-02-24 18:28:40.896854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bace61fe2b79'
down_revision = '055c6a993116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userinfo', 'email',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userinfo', 'email',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
